spring.current.env=beta
spring.datasource.url=jdbc:mysql://databricks-schema-management.ckr6oyyfiopw.us-west-2.rds.amazonaws.com:3306/databricks_metadata_beta
spring.datasource.username=dsm
spring.datasource.password=tR9tecuph3pr
springdoc.api-docs.path=/api-docs
databricks.api.url=https://dbc-f7dd24b7-5870.cloud.databricks.com/api/2.1/unity-catalog/tables/
databricks.api.token.secret=power_user
databricks.s3path.cleanup-threshold-days=30
databricks.aws.secret=databricks/beta/databricks_schema_management_tool
databricks.s3.location=s3://776819311813-ciq-catalog-beta/catalogs/{catalog}/{schema}/{table_name}/v1
databricks.delta.deletedFileRetentionDuration=interval 1 days
databricks.delta.logRetentionDuration=interval 1 days