spring.current.env=prod
spring.datasource.url=jdbc:mysql://databricks-schema-management.ckr6oyyfiopw.us-west-2.rds.amazonaws.com:3306/databricks_metadata_prod
spring.datasource.username=dsm
spring.datasource.password=tR9tecuph3pr
springdoc.api-docs.path=/api-docs
databricks.api.url=https://dbc-b3e2823d-6d7a.cloud.databricks.com/api/2.1/unity-catalog/tables/
databricks.api.token.secret=power_user
databricks.s3path.cleanup-threshold-days=30
databricks.aws.secret=databricks/prod/databricks_schema_management_tool
databricks.s3.location=s3://776819311813-ciq-catalog-prod/catalogs/{catalog}/{schema}/{table_name}/v1
databricks.delta.deletedFileRetentionDuration=interval 3 days
databricks.delta.logRetentionDuration=interval 3 days